### ISSUE TITLE
decorate the forgot password button

### ISSUE THREAD

**Issue by Krishna1922** [Krishna1922/facebook-login-page#1]
you have to decorate the forgot password button
![image](https://user-images.githubusercontent.com/92522740/195925815-3a06e028-04df-4089-be59-b405724c8b31.png)

**Comment by 72002sweta** [comment]
do you just want it change the font and colour or is there any other demands??
 anyways please assign i can work on it

**Comment by prernadabi23** [comment]
can i work on this issue?

**Comment by Krishna1922** [comment]
gyzz.. this issue is already has completed by @dhanrajchaurasia so im closing this issue
dont worry im creating new issue

**Comment by Krishna1922** [comment]
u can work on their

**Comment by Krishna1922** [comment]
gyz.. this issue is already completed by @dhanrajchaurasia so I m closing this issue now
dont worry I m creating new issues so u can work their
