### ISSUE TITLE
create a contact us and about

### ISSUE THREAD

**Issue by Krishna1922** [Krishna1922/facebook-login-page#3]
create a contact us and about below login button

**Comment by zainulabideen1122** [comment]
@Krishna1922 hey , can you assign this task to me, i would like to work on this task

**Comment by zainulabideen1122** [comment]
@Krishna1922 , hey i am creating a pull request, kindly check it out
Here is what i made:

About us page:

![2](https://user-images.githubusercontent.com/59528492/196005606-e1af2682-96b2-469f-8e40-fe3d347c3592.png)

Contact us page:

![1](https://user-images.githubusercontent.com/59528492/196005618-89815241-9734-4e08-89ee-487b904dc6f6.png)

**Comment by Krishna1922** [comment]
Does the backbground of both the pages are matching with login page theme?? @zainulabideen1122

**Comment by zainulabideen1122** [comment]
Check it out now:

![4](https://user-images.githubusercontent.com/59528492/196020955-b622b1ee-a595-4611-b3e0-3268138b0720.png)



![3](https://user-images.githubusercontent.com/59528492/196020956-d3d8d043-dca5-457f-a94b-bd70181ec42f.png)
